# Data sources

Our dataset is collected from a website called “Chanmama" (https://www.chanmama.com/), which is the largest database that collects and distributes data about live stream e-commerce taking place in the Chinese version of TikTok “Douyin”. It provides data that includes some general information of the live hosts, the detailed revenue of each live stream, and information on the products sold during each live stream. However, since this database currently only covers data about the Chinese version of TikTok, it is only available in Chinese, which means some additional translations are required. Also, we had to register and subscribe first to gain access to the data.

The raw data is in Excel format, and it is located under each live host’s profile. Each live host has three own Excel files storing the data focusing on three different areas, and we can only download the files one by one instead of in just one step. We take advantage of the sales revenue ranking system provided by the database to see who the Top 20 live hosts in terms of sales revenue during June, July, and August of 2021 are. Then, we manually download the data files from these 20 live host profiles and then combine them into three single Excel files. 

The first Excel file is named as Data_Livestream_General, and it includes some general information about each past live stream of the hosts. To help our analysis, we decide to add 3 additional columns to the dataset, including the host’s full name (Name), whether is an online KOL or celebrity (Host_category), and the host’s previous occupation (Occupation). This information is more categorical and available in each host’s profile, but the raw data doesn’t contain it. After the adjustment, there are a total of 21 variables and 20000 more observations in this dataset, but we use them selectively. These variables mainly are numeric data, such as the start time of live steam, the number of products presented, the number of goods sold, total sales amount, duration, views, and the average length of stay. It also includes a few character data such as the name of the live stream, the host’s name, and the occupation.

The second Excel file is named as Data_Sales, and it includes some more detailed information about the specific goods sold by the 20 hosts. Again, to help our analysis, we add the host’s full name as an additional identifier column. After the adjustment, there are a total of 9 variables and more than 10000 observations. These variables include two categorical data, the goods category, and the host’s name. The rest five variables are all numeric data, including a specific good’s retailing price in the Chinese Yuan, its commission rate, sales volume. sales amount, conversion rate, the number of appearances on short videos, and the number of appearances on live streaming.

The third Excel file is named as Data_Short_Videos, and it gives us information about the top 20 hosts' data regarding their posted short videos. It includes a total of 9 variables and 18051 observations in total. Just like in the previous data file, we added in an additional identifier column (name) to the original raw data.This data set tells us information such as Video content release time, the video duration, estimated Sales volume (pieces)	estimated sales amount, Number of likes,	Number of comments, Number of reposts	Name.
