# Conclusion

To sum up, we researched the topic of Chinese Tiktok live streaming through three completely different perspectives, which include celebrities versus KOLs, the relationship between short video feedback to the live streaming sales, and also time's influence on the live streaming sales.

During our research, based on our data visualization and analysis, we found several interesting and noteworthy observations:

1.
In general, consumers came to KOL because they have expertise in a specific category and came to celebrities because of their reputation. Therefore, the answer to the question of whether celebrities have advantages over KOLs in live streaming sales is ambiguous, as both groups have their special features and are appealing to their specific targeting viewer.

2.
When a lot of people like or comment on a hosts’ videos, the live streamings of that hosts are more likely to become popular and generate more revenues. The reason might be viewers who like or comment on a host’s video would probably lead to their further actions of going into the host’s live streaming room and checking out what the host is presenting and selling. However, for celebrities, this action of going into hosts’ room would more likely in tolt in people actually buying stuff, while this is not that true for KOLs.

3.
No matter the host is a KOL or a celebrity, an average stay length of 2.5 minutes in the live streaming room appears to be the best choice to boost the room's sales amount. Also, live streaming started around 10 AM tends to have a longer live streaming duration, and they also tend to result in a higher average total sales amounts than those started at other hours. In addition, selling on weekends is more likely to increase sales amounts, whereas selling on Monday and Thursday might be less favorable choices.

However, we understand that our analysis is fairly fundamental and has many limitations. For instance, there are a few obvious outliers that existed in our datasets, such as Jia Nailiang, a famous Chinese celebrity known for his affairs, who just started entering this industry and live-streamed not that frequently in the past three months. Nevertheless, he still achieved a very high level of sales amount, greatly surpassing a lot of other hosts who have already been in this industry for many years. We will continue to track his progress and to see if he can still maintain his efficiency and popularity in the next couple of months. In addition, we realized nowadays, it is really challenging to tell the boundary between KOLs and celebrities, as more and more celebrities started to use the Internet as the main method to promote their status and to expand their influence. A typical example is Luo Yonghao, who is famous for his failing entrepreneurship in his early life, actively participates in online events and takes them as an opportunity to expand his influence. We might need additional scrutiny in the future.
