--- 
title: "Tiktok Livesale Edav Project"
author: "Jessie Wang, Jingyuan Chen, Megan Zhou"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The concept of live e-commerce might be very new to people in US, but in China, where live e-commerce market is huge, a good host can generate millions in sales in just a few hours. In fact, by March 2020, the number of live commerce users had reached 265 million, accounting for 29.3% of the country’s total number of internet users, and that was only before COVID-19 hit. 
By deep-diving into the data and reflecting on some trends and patterns that live e-commerce has in China, out group wish to generate an analysis that will be helpful for anyone who is interested in starting steaming commerce business in the US. 
One of the most popular platforms for live commerce in China is called ''Douyin'', the Chinese version of Tiktok with more features available. There is a website called "Chanmama" (https://www.chanmama.com/) that collects and distributes data about live commerce happening on Douyin. Based on data fetched from the website, we will focus our study on how hosts, products, live streaming timing, and related short-videos impacted the total revenue generated from the live e-commerce. Although everyone is able to sell products on Douyin, most revenues are generated by hosts who are either celebrities or key opinion leaders (KOLs). In our analysis, celebrities are defined as famous singers/actors/actresses in China who are known by the public before starting the live streaming sales and KOLs are those who are known as a result of live-streaming sales or publishing short videos on Douyin. The difference between those two groups is compared throughout our project and we will mainly study the top 20 hosts ranked by revenue generated. 